-- ========================================================
-- Series Update - Supabase Database Schema & Setup Script
-- Project URL: https://itesblkjljdsulbtdeon.supabase.co
-- ========================================================

-- 1. Create content table (Movies & Series)
CREATE TABLE IF NOT EXISTS public.content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    type TEXT DEFAULT 'Movie',
    thumb_portrait TEXT,
    thumb_landscape TEXT,
    category TEXT,
    description TEXT,
    publish_date TEXT,
    featured BOOLEAN DEFAULT FALSE,
    quality TEXT DEFAULT '1080p Full HD',
    video_link TEXT,
    android_link TEXT,
    ios_link TEXT,
    download_link TEXT,
    embed_code TEXT,
    embed_code2 TEXT,
    embed_code3 TEXT,
    episodes JSONB DEFAULT '[]'::jsonb
);

-- 2. Create products table (Affiliate Shopping)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    image_url TEXT,
    category TEXT,
    price TEXT,
    original_price TEXT,
    discount_percentage INT,
    affiliate_url TEXT,
    description TEXT,
    featured BOOLEAN DEFAULT FALSE,
    status BOOLEAN DEFAULT TRUE
);

-- 3. Create ads table (Global Ad Banners)
CREATE TABLE IF NOT EXISTS public.ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    position TEXT NOT NULL,
    image_url TEXT,
    link_url TEXT,
    script_code TEXT,
    display_order INT DEFAULT 0,
    status BOOLEAN DEFAULT TRUE
);

-- 4. Create wallet_balance table
CREATE TABLE IF NOT EXISTS public.wallet_balance (
    id BIGINT PRIMARY KEY DEFAULT 1,
    balance NUMERIC DEFAULT 0.00
);

-- 5. Create withdrawals table
CREATE TABLE IF NOT EXISTS public.withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    amount NUMERIC,
    upi_id TEXT,
    status TEXT DEFAULT 'pending'
);

-- Enable Row Level Security (RLS) on all tables and grant full permissions to anon & authenticated users
ALTER TABLE public.content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallet_balance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.withdrawals ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (Read, Insert, Update, Delete)
DROP POLICY IF EXISTS "Public Read Content" ON public.content;
CREATE POLICY "Public Read Content" ON public.content FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert Content" ON public.content;
CREATE POLICY "Public Insert Content" ON public.content FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Update Content" ON public.content;
CREATE POLICY "Public Update Content" ON public.content FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Delete Content" ON public.content;
CREATE POLICY "Public Delete Content" ON public.content FOR DELETE USING (true);

-- Products Policies
DROP POLICY IF EXISTS "Public Read Products" ON public.products;
CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert Products" ON public.products;
CREATE POLICY "Public Insert Products" ON public.products FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Update Products" ON public.products;
CREATE POLICY "Public Update Products" ON public.products FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Delete Products" ON public.products;
CREATE POLICY "Public Delete Products" ON public.products FOR DELETE USING (true);

-- Ads Policies
DROP POLICY IF EXISTS "Public Read Ads" ON public.ads;
CREATE POLICY "Public Read Ads" ON public.ads FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert Ads" ON public.ads;
CREATE POLICY "Public Insert Ads" ON public.ads FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Update Ads" ON public.ads;
CREATE POLICY "Public Update Ads" ON public.ads FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Delete Ads" ON public.ads;
CREATE POLICY "Public Delete Ads" ON public.ads FOR DELETE USING (true);

-- Wallet Balance & Withdrawals Policies
DROP POLICY IF EXISTS "Public Wallet Balance" ON public.wallet_balance;
CREATE POLICY "Public Wallet Balance" ON public.wallet_balance FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Withdrawals" ON public.withdrawals;
CREATE POLICY "Public Withdrawals" ON public.withdrawals FOR ALL USING (true);

-- Insert Initial Default Seed Content
INSERT INTO public.wallet_balance (id, balance) VALUES (1, 0.00) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.content (title, type, thumb_portrait, thumb_landscape, category, description, publish_date, featured, quality, video_link, episodes)
VALUES 
(
    'Heart Beat 2026 Season 03',
    'Series',
    'https://i.ibb.co/S4mxsbrc/Chat-GPT-Image-Jun-7-2026-02-04-20-PMG.png',
    'https://i.ibb.co/S4mxsbrc/Chat-GPT-Image-Jun-7-2026-02-04-20-PMG.png',
    'Drama',
    'Heart Beat Season 3 is a Tamil medical drama series featuring dramatic twists and emotional storylines.',
    '2026-07-30',
    true,
    '4K Ultra HD',
    'https://www.youtube.com/embed/dQw4w9WgXcQ',
    '[{"title": "Episode 1: New Beginnings", "videoLink": "https://www.youtube.com/embed/dQw4w9WgXcQ"}, {"title": "Episode 2: Critical Condition", "videoLink": "https://www.youtube.com/embed/dQw4w9WgXcQ"}]'::jsonb
),
(
    'Leo',
    'Movie',
    'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&q=80',
    'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1000&q=80',
    'Action',
    'A cafe owner in a quiet town becomes an unexpected hero after thwarting a robbery, drawing violent figures from his past.',
    '2026-06-15',
    true,
    '4K Ultra HD',
    'https://www.youtube.com/embed/dQw4w9WgXcQ',
    '[]'::jsonb
),
(
    'Jailer',
    'Movie',
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&q=80',
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1000&q=80',
    'Action',
    'A retired prison warden sets out to rescue his son and avenge his family, taking on an international syndicate.',
    '2026-05-10',
    false,
    '1080p Full HD',
    'https://www.youtube.com/embed/dQw4w9WgXcQ',
    '[]'::jsonb
),
(
    'Cyber City 2099',
    'Series',
    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&q=80',
    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1000&q=80',
    'Sci-Fi',
    'In a dystopian metropolis, a rogue hacker uncovers a conspiracy that threatens humanity.',
    '2026-04-20',
    true,
    '4K Ultra HD',
    'https://www.youtube.com/embed/dQw4w9WgXcQ',
    '[{"title": "Episode 1: Glitch", "videoLink": "https://www.youtube.com/embed/dQw4w9WgXcQ"}]'::jsonb
),
(
    'Shadow Hunter',
    'Movie',
    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&q=80',
    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1000&q=80',
    'Thriller',
    'A detective with a troubled past tracks a phantom assassin operating in the dark underbelly of the city.',
    '2026-03-12',
    false,
    '1080p Full HD',
    'https://www.youtube.com/embed/dQw4w9WgXcQ',
    '[]'::jsonb
),
(
    'Pushpa 2: The Rule',
    'Movie',
    'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&q=80',
    'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1000&q=80',
    'Upcoming',
    'The clash between Pushpa Raj and Bhanwar Singh continues as Pushpa expands his red sandalwood empire globally.',
    '2026-12-05',
    true,
    '4K Ultra HD',
    'https://www.youtube.com/embed/dQw4w9WgXcQ',
    '[]'::jsonb
),
(
    'Stranger Things Season 5',
    'Series',
    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&q=80',
    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1000&q=80',
    'Upcoming',
    'The final battle for Hawkins begins as Eleven and her friends join forces to destroy Vecna once and for all.',
    '2026-11-20',
    true,
    '4K Ultra HD',
    'https://www.youtube.com/embed/dQw4w9WgXcQ',
    '[]'::jsonb
)
ON CONFLICT DO NOTHING;
